// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2wzuspxjfEEX_NNc7hhgvGTdDJFGclgw',
    appId: '1:363238450440:web:36bbd83df1add1ad49b8bd',
    messagingSenderId: '363238450440',
    projectId: 'tokio-app-772d0',
    authDomain: 'tokio-app-772d0.firebaseapp.com',
    databaseURL: 'https://tokio-app-772d0-default-rtdb.firebaseio.com',
    storageBucket: 'tokio-app-772d0.firebasestorage.app',
    measurementId: 'G-Y2DK615680',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9xFwpR4bV9YL9WHroczy_p7RXAu7YbfM',
    appId: '1:363238450440:android:7f58628baa7a627249b8bd',
    messagingSenderId: '363238450440',
    projectId: 'tokio-app-772d0',
    databaseURL: 'https://tokio-app-772d0-default-rtdb.firebaseio.com',
    storageBucket: 'tokio-app-772d0.firebasestorage.app',
  );

}